// Code generated by mockery v2.50.4. DO NOT EDIT.

package mocks

import (
	io "io"

	model "github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model"
	mock "github.com/stretchr/testify/mock"
)

// PdfCpuApi is an autogenerated mock type for the PdfCpuApi type
type PdfCpuApi struct {
	mock.Mock
}

// Optimize provides a mock function with given fields: rs, w, conf
func (_m *PdfCpuApi) Optimize(rs io.ReadSeeker, w io.Writer, conf *model.Configuration) error {
	ret := _m.Called(rs, w, conf)

	if len(ret) == 0 {
		panic("no return value specified for Optimize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(io.ReadSeeker, io.Writer, *model.Configuration) error); ok {
		r0 = rf(rs, w, conf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPdfCpuApi creates a new instance of PdfCpuApi. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPdfCpuApi(t interface {
	mock.TestingT
	Cleanup(func())
}) *PdfCpuApi {
	mock := &PdfCpuApi{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
