// Code generated by mockery v2.50.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/bxcodec/go-clean-arch/domain"
	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"
)

// PdfService is an autogenerated mock type for the PdfService type
type PdfService struct {
	mock.Mock
}

// CompressPdf provides a mock function with given fields: ctx, fileName, file
func (_m *PdfService) CompressPdf(ctx context.Context, fileName string, file multipart.File) (domain.PdfFile, error) {
	ret := _m.Called(ctx, fileName, file)

	if len(ret) == 0 {
		panic("no return value specified for CompressPdf")
	}

	var r0 domain.PdfFile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, multipart.File) (domain.PdfFile, error)); ok {
		return rf(ctx, fileName, file)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, multipart.File) domain.PdfFile); ok {
		r0 = rf(ctx, fileName, file)
	} else {
		r0 = ret.Get(0).(domain.PdfFile)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, multipart.File) error); ok {
		r1 = rf(ctx, fileName, file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPdfService creates a new instance of PdfService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPdfService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PdfService {
	mock := &PdfService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
