basePath: /
definitions:
  rest.ResponseError:
    properties:
      message:
        type: string
    type: object
host: localhost:9090
info:
  contact: {}
  description: This is a sample server for using Swagger with Echo.
  title: Swagger Example API
  version: "1.0"
paths:
  /process/compress:
    post:
      consumes:
      - multipart/form-data
      description: This API compresses the provided PDF file and returns the compressed
        version.
      parameters:
      - description: PDF file
        in: formData
        name: file
        required: true
        type: file
      responses:
        "200":
          description: Compressed PDF file
          schema:
            type: file
        "400":
          description: File type is invalid
          schema:
            $ref: '#/definitions/rest.ResponseError'
        "500":
          description: Failed to compress PDF
          schema:
            $ref: '#/definitions/rest.ResponseError'
      summary: Compress a PDF file
      tags:
      - PDF
swagger: "2.0"
