// Code generated by mockery v2.50.4. DO NOT EDIT.

package mocks

import (
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"
)

// PdfRepository is an autogenerated mock type for the PdfRepository type
type PdfRepository struct {
	mock.Mock
}

// Compress provides a mock function with given fields: file
func (_m *PdfRepository) Compress(file multipart.File) ([]byte, error) {
	ret := _m.Called(file)

	if len(ret) == 0 {
		panic("no return value specified for Compress")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(multipart.File) ([]byte, error)); ok {
		return rf(file)
	}
	if rf, ok := ret.Get(0).(func(multipart.File) []byte); ok {
		r0 = rf(file)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(multipart.File) error); ok {
		r1 = rf(file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPdfRepository creates a new instance of PdfRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPdfRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PdfRepository {
	mock := &PdfRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
